version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
  pre_build:
    commands:
      - echo Installing...
      - pip install -r src/requirements.txt
      - export PYTHONPATH=`realpath ./src/`
  build:
    commands:
      - echo Testing...
      - python -m unittest discover --start-directory ./tests/
      - echo Building...
      - sam build
      - sam deploy --no-confirm-changeset --debug
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/messageUtil-1.0.jar