AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: >
  Serverless application that periodically scrapes guardian 
  website for favourable reviews and puts them into a trakt list.

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.10
      Timeout: 30
      Environment:
        Variables:
          MANUAL_PROCESSING_QUEUE_URL: !Ref ManualProcessingQueue
      Policies:
        - SQSSendMessagePolicy:
            QueueName:
              !GetAtt ManualProcessingQueue.QueueName

  ScheduledRule: 
    Type: AWS::Events::Rule
    Properties: 
      Description: "ScheduledRule"
      ScheduleExpression: "cron(0 0 * * ? *)"
      State: "ENABLED"
      Targets: 
        - Arn: !GetAtt LambdaFunction.Arn
          Id:
            Ref: "LambdaFunction"

  InvokeLambdaPermission: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: !GetAtt LambdaFunction.Arn
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt ScheduledRule.Arn

  ManualProcessingQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      MessageRetentionPeriod: 604800 # 7 days.
      QueueName: "GoodFilms--RequireManualProcessing"
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete

Outputs:
  LambdaFunction:
    Description: "Guardian Films Lambda Function ARN"
    Value: !GetAtt LambdaFunction.Arn
  LambdaFunctionIamRole:
    Description: "Implicit IAM Role created for Guardian Films function"
    Value: !GetAtt LambdaFunctionRole.Arn
