AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: >
  Serverless application that periodically scrapes guardian 
  website for favourable reviews and puts them into a trakt list.

Resources:
  GuardianFilmsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: guardian_films/
      Handler: app.lambda_handler
      Runtime: python3.6

Outputs:
  GuardianFilmsFunction:
    Description: "Guardian Films Lambda Function ARN"
    Value: !GetAtt GuardianFilmsFunction.Arn
  GuardianFilmsFunctionIamRole:
    Description: "Implicit IAM Role created for Guardian Films function"
    Value: !GetAtt GuardianFilmsFunctionRole.Arn
