AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: >
  Serverless application that periodically scrapes guardian 
  website for favourable reviews and puts them into a trakt list.

Resources:
  GuardianLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: guardian/
      Handler: app.lambda_handler
      Runtime: python3.10
      Timeout: 30
      Environment:
        Variables:
          GUARDIAN_ARTICLE_QUEUE_URL: !Ref GuardianArticleQueue
      Policies:
        - SQSSendMessagePolicy:
            QueueName:
              !GetAtt GuardianArticleQueue.QueueName

  TraktLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: trakt/
      Handler: app.lambda_handler
      Runtime: python3.10
      Timeout: 30
      Events:
        SQSQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt GuardianArticleQueue.Arn
      Environment:
        Variables:
          UNPROCESSABLE_QUEUE_URL: !Ref UnprocessableQueue
      Policies:
        - SQSSendMessagePolicy:
            QueueName:
              !GetAtt UnprocessableQueue.QueueName


  ScheduledRule: 
    Type: AWS::Events::Rule
    Properties: 
      Description: "ScheduledRule"
      ScheduleExpression: "cron(0 0 * * ? *)"
      State: "ENABLED"
      Targets: 
        - Arn: !GetAtt GuardianLambdaFunction.Arn
          Id:
            Ref: "GuardianLambdaFunction"

  InvokeLambdaPermission: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: !GetAtt GuardianLambdaFunction.Arn
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt ScheduledRule.Arn

  UnprocessableQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      MessageRetentionPeriod: 604800 # 7 days.
      QueueName: "GoodFilms--UnprocessableGuardianArticles"
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete

  GuardianArticleQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      MessageRetentionPeriod: 604800 # 7 days.
      QueueName: "GoodFilms--GuardianArticles"
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete

Outputs:
  GuardianLambdaFunction:
    Description: "Guardian Lambda Function ARN"
    Value: !GetAtt GuardianLambdaFunction.Arn
  TraktLambdaFunction:
    Description: "Trakt Lambda Function ARN"
    Value: !GetAtt TraktLambdaFunction.Arn
  LambdaFunctionIamRole:
    Description: "Implicit IAM Role created for Guardian Films function"
    Value: !GetAtt GuardianLambdaFunction.Arn
