AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: >
  Serverless application that periodically scrapes guardian 
  website for favourable reviews and puts them into a trakt list.

Resources:
  GuardianLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: guardian/
      Handler: app.lambda_handler
      Runtime: python3.10
      Timeout: 30
      Environment:
        Variables:
          GUARDIAN_ARTICLE_QUEUE_URL: !Ref GuardianArticleQueue
      Policies:
        - SQSSendMessagePolicy:
            QueueName:
              !GetAtt GuardianArticleQueue.QueueName
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:eu-west-2:680611375585:secret:GuardianAPI-LnBR6M"
        - SSMParameterReadPolicy:
            ParameterName: "GoodFilms_LastSuccess"
        - Statement:
            - Sid: SSMParameterWritePolicy
              Effect: Allow
              Action:
                - ssm:PutParameter
              Resource: >-
                arn:aws:ssm:eu-west-2:680611375585:parameter/GoodFilms_LastSuccess
  TraktLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: trakt/
      Handler: app.lambda_handler
      Runtime: python3.10
      Timeout: 30
      ReservedConcurrentExecutions: 1
      Events:
        SQSQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt GuardianArticleQueue.Arn
            BatchSize: 1
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:eu-west-2:680611375585:secret:TraktAPI-BFbWUe"


  ScheduledRule: 
    Type: AWS::Events::Rule
    Properties: 
      Description: "ScheduledRule"
      ScheduleExpression: "cron(0 0 * * ? *)"
      State: "ENABLED"
      Targets: 
        - Arn: !GetAtt GuardianLambdaFunction.Arn
          Id:
            Ref: "GuardianLambdaFunction"

  InvokeLambdaPermission: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: !GetAtt GuardianLambdaFunction.Arn
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt ScheduledRule.Arn

  GuardianArticleDLQ:
    Type: "AWS::SQS::Queue"
    Properties:
      MessageRetentionPeriod: 604800 # 7 days.
      QueueName: "GoodFilms--GuardianArticleDLQ"
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete

  GuardianArticleQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      MessageRetentionPeriod: 604800 # 7 days.
      QueueName: "GoodFilms--GuardianArticles"
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt GuardianArticleDLQ.Arn
        maxReceiveCount: 3

    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete

Outputs:
  GuardianLambdaFunction:
    Description: "Guardian Lambda Function ARN"
    Value: !GetAtt GuardianLambdaFunction.Arn
  TraktLambdaFunction:
    Description: "Trakt Lambda Function ARN"
    Value: !GetAtt TraktLambdaFunction.Arn
  LambdaFunctionIamRole:
    Description: "Implicit IAM Role created for Guardian Films function"
    Value: !GetAtt GuardianLambdaFunction.Arn
