AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: >
  A stack template that incorporates all our lambdas.
  Work in Progress.

Parameters:
  GuardianApiKey:
    Type: String
  GuardianLastSuccess:
    Type: String

  TraktClientId:
    Type: String
  TraktClientSecret:
    Type: String
  TraktAccessToken:
    Type: String
  TraktRefreshToken:
    Type: String
  TraktUserId:
    Type: String
  TraktListId:
    Type: String
  TraktMaxListSize:
    Type: String

Resources:
  GuardianService:
    Type: AWS::Serverless::Application
    Properties:
      Location: guardian/template.yaml
      Parameters:
        DestinationQueueArn: !GetAtt ArticleQueue.Arn
        DestinationQueueUrl: !GetAtt ArticleQueue.QueueUrl
        ApiKey: !Ref GuardianApiKey
        LastSuccess: !Ref GuardianLastSuccess

  TraktService:
    Type: AWS::Serverless::Application
    Properties:
      Location: trakt/template.yaml
      Parameters:
        SourceQueueArn: !GetAtt ArticleQueue.Arn

        ClientId: !Ref TraktClientId
        ClientSecret: !Ref TraktClientSecret
        AccessToken: !Ref TraktAccessToken
        RefreshToken: !Ref TraktRefreshToken

        UserId: !Ref TraktUserId
        ListId: !Ref TraktListId
        MaxListSize: !Ref TraktMaxListSize

  ArticleDLQ:
    Type: "AWS::SQS::Queue"
    Properties:
      MessageRetentionPeriod: 604800 # 7 days.
      QueueName: "GoodFilms--ArticleDLQ"
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete

  ArticleQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      MessageRetentionPeriod: 604800 # 7 days.
      QueueName: "GoodFilms--GuardianArticles"
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ArticleDLQ.Arn
        maxReceiveCount: 3
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
