AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model template describing your function.
Resources:
  TraktTokenRotator:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src/
      Timeout: 3
      Handler: lambda_function.lambda_handler
      Runtime: python3.10
      PackageType: Zip
      Policies:
        - Statement:
            - Sid: AllowLambdaToStoreAndRetrieveSecrets
              Effect: Allow
              Action:
                - secretsmanager:DescribeSecret
                - secretsmanager:GetSecretValue
                - secretsmanager:PutSecretValue
                - secretsmanager:UpdateSecretVersionStage
              Resource: >-
                arn:aws:secretsmanager:eu-west-2:680611375585:secret:TraktAPI-BFbWUe
            - Sid: RecordProgressInLogsForEasierDebugging
              Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'
      RecursiveLoop: Terminate
      SnapStart:
        ApplyOn: None
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
