AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: >
  Serverless application that periodically scrapes guardian 
  website for favourable reviews and puts them into a Queue.

Parameters:
  DestinationQueueArn:
    Type: String
  DestinationQueueUrl:
    Type: String
  ApiKey:
    Type: String
  LastSuccess:
    Type: String

Resources:
  Lambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.14
      Timeout: 30
      Environment:
        Variables:
          GUARDIAN_ARTICLE_QUEUE_URL: !Ref DestinationQueueUrl
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref Secret
        - SSMParameterReadPolicy:
            ParameterName: !Ref Parameter
        - Statement:
          - Sid: SSMParameterWritePolicy
            Effect: Allow
            Action:
              - ssm:PutParameter
            Resource: !Sub arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter${Parameter}
        - Statement:
          - Effect: Allow
            Action:
              - sqs:SendMessage
            Resource: !Ref DestinationQueueArn

      Events:
        DailySchedule:
          Type: ScheduleV2
          Properties:
            ScheduleExpression: "cron(0 0 * * ? *)"

  Secret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Use to access https://content.guardianapis.com
      Name: /GoodFilms/GuardianAPI
      SecretString: !Sub '{"API_KEY":"${ApiKey}"}'

  Parameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /GoodFilms/LastSuccess
      Type: String
      Value: !Ref LastSuccess

Outputs:
  LambdaArn:
    Description: "Guardian Lambda Function ARN"
    Value: !GetAtt Lambda.Arn
